FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# 1. Install Dependencies
# Added explicit library support for Samba
RUN apt-get update && apt-get install -y \
    libpopt-dev libreadline-dev zlib1g-dev libssl-dev libncurses5-dev \
    libsasl2-dev libkrb5-dev liblmdb-dev \
    libsocket-wrapper libuid-wrapper libnss-wrapper libpam-wrapper \
    build-essential rsync wget curl \
    python3 python3-dev libdw-dev libunwind-dev \
    python2 python2-dev \
    flex bison git pkg-config libelf-dev python3-pip \
    libparse-yapp-perl perl libgnutls28-dev python3-cryptography \
    libacl1-dev libldap2-dev libpam0g-dev libcups2-dev \
    libbsd-dev libjansson-dev libarchive-dev libicu-dev \
    libtirpc-dev libdbus-1-dev \
    && rm -rf /var/lib/apt/lists/* \
    && git clone --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git \
    && cd linux/tools/perf \
    && NO_JEVENTS=1 NO_LIBTRACEEVENT=1 make \
    && cp perf /usr/bin \
    && cd / && rm -rf linux

# 2. Force 'python' to map to Python 2 (Required for old Samba Waf scripts)
RUN ln -sf /usr/bin/python2 /usr/bin/python

COPY requirements.txt /app/
RUN pip3 install --no-cache-dir -r /app/requirements.txt

WORKDIR /app
RUN git clone https://github.com/samba-team/samba.git /app/inputs/samba

COPY samba_pipeline.py /app/
CMD ["python3", "samba_pipeline.py"]