FROM ubuntu:24.04

# 1. Install Dependencies
# Added: libglib2.0-dev, libpixman-1-dev (Core QEMU deps), ninja-build (for modern QEMU)
RUN apt-get update && apt-get install -y \
    build-essential rsync wget curl \
    python3 python3-dev libdw-dev libunwind-dev \
    flex bison git pkg-config libelf-dev libtraceevent-dev python3-pip \
    libglib2.0-dev libpixman-1-dev ninja-build \
    && rm -rf /var/lib/apt/lists/* \
    && git clone --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git \
    && cd linux/tools/perf \
    && NO_JEVENTS=1 make \
    && cp perf /usr/bin \
    && cd / && rm -rf linux

COPY requirements.txt /app/
RUN pip3 install --no-cache-dir --break-system-packages -r /app/requirements.txt

WORKDIR /app

# ------------------------------------------------------------------
# DOWNLOAD RESOURCES
# ------------------------------------------------------------------

# Download QEMU Repo (Bonzini Fork)
RUN git clone https://github.com/bonzini/qemu.git /app/inputs/qemu

# ------------------------------------------------------------------

COPY qemu_pipeline.py /app/

CMD ["python3", "qemu_pipeline.py"]