# Using Ubuntu 20.04 for compatibility with older Libarchive commits
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# Install VFEC Core + Libarchive Specific Dependencies
# Libarchive requires: cmake, zlib, bzip2, lzma, lz4, zstd, openssl, xml2, expat
RUN apt-get update && apt-get install -y \
    build-essential rsync wget curl \
    python3 python3-dev libdw-dev libunwind-dev \
    flex bison git pkg-config libelf-dev python3-pip \
    cmake autoconf automake libtool \
    zlib1g-dev libbz2-dev liblzma-dev liblz4-dev libzstd-dev \
    libssl-dev libxml2-dev libexpat1-dev \
    && rm -rf /var/lib/apt/lists/* \
    && git clone --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git \
    && cd linux/tools/perf \
    && NO_JEVENTS=1 NO_LIBTRACEEVENT=1 make \
    && cp perf /usr/bin \
    && cd / && rm -rf linux

COPY requirements.txt /app/
RUN pip3 install --no-cache-dir -r /app/requirements.txt

WORKDIR /app

# Download Libarchive Repo
RUN git clone https://github.com/libarchive/libarchive.git /app/inputs/libarchive

COPY libarchive_pipeline.py /app/

CMD ["python3", "libarchive_pipeline.py"]