# Using Ubuntu 20.04 for compatibility with older Autotools scripts
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV USER=root

# Install VFEC Core + libexpat Specific Dependencies
# libexpat deps: autoconf, automake, libtool, check (unit tests)
RUN apt-get update && apt-get install -y \
    build-essential rsync wget curl \
    python3 python3-dev python-is-python3 libdw-dev libunwind-dev \
    flex bison git pkg-config libelf-dev python3-pip \
    autoconf automake libtool libtool-bin check \
    && rm -rf /var/lib/apt/lists/* \
    && git clone --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git \
    && cd linux/tools/perf \
    && NO_JEVENTS=1 NO_LIBTRACEEVENT=1 make \
    && cp perf /usr/bin \
    && cd / && rm -rf linux

COPY requirements.txt /app/
RUN pip3 install --no-cache-dir -r /app/requirements.txt

WORKDIR /app

# Download libexpat Repo
RUN git clone https://github.com/libexpat/libexpat.git /app/inputs/libexpat

COPY libexpat_pipeline.py /app/

CMD ["python3", "libexpat_pipeline.py"]