# Using Ubuntu 20.04 for compatibility with older curl Autotools commits
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
# [FIX] Set a fake USER variable for curl's Perl test scripts
ENV USER=root

# Install VFEC Core + curl Specific Dependencies
# [FIX] Added 'python-is-python3', 'perl', and 'm4' for older curl buildconf/test scripts
RUN apt-get update && apt-get install -y \
    build-essential rsync wget curl \
    python3 python3-dev python-is-python3 libdw-dev libunwind-dev \
    flex bison git pkg-config libelf-dev python3-pip \
    autoconf automake libtool m4 perl \
    libssl-dev zlib1g-dev libssh2-1-dev libidn2-dev \
    libbrotli-dev libzstd-dev \
    && rm -rf /var/lib/apt/lists/* \
    && git clone --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git \
    && cd linux/tools/perf \
    && NO_JEVENTS=1 NO_LIBTRACEEVENT=1 make \
    && cp perf /usr/bin \
    && cd / && rm -rf linux

COPY requirements.txt /app/
RUN pip3 install --no-cache-dir -r /app/requirements.txt

WORKDIR /app

# Download curl Repo
RUN git clone https://github.com/curl/curl.git /app/inputs/curl

COPY curl_pipeline.py /app/

CMD ["python3", "curl_pipeline.py"]