# Dockerfile_krb5
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# 1. Install Dependencies
# Added: python3-pyrad (Fixes 'pyrad not found' test failures)
RUN apt-get update && apt-get install -y \
    build-essential rsync wget curl \
    python3 python3-dev libdw-dev libunwind-dev \
    flex bison git pkg-config libelf-dev python3-pip \
    autoconf automake libtool \
    libssl-dev libldap2-dev gettext tcl-dev \
    libcap-dev libzstd-dev libnuma-dev \
    python3-pyrad \
    && rm -rf /var/lib/apt/lists/* \
    && git clone --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git \
    && cd linux/tools/perf \
    && NO_JEVENTS=1 NO_LIBTRACEEVENT=1 make \
    && cp perf /usr/bin \
    && cd / && rm -rf linux

COPY requirements.txt /app/
RUN pip3 install --no-cache-dir -r /app/requirements.txt

WORKDIR /app

# Download krb5 Repo
RUN git clone https://github.com/krb5/krb5.git /app/inputs/krb5

COPY krb5_pipeline.py /app/

CMD ["python3", "krb5_pipeline.py"]