FROM ubuntu:24.04

# 1. Install Dependencies
# ADDED: autoconf, automake, libtool (CRITICAL for ./buildconf)
RUN apt-get update && apt-get install -y \
    build-essential rsync wget curl \
    python3 python3-dev libdw-dev libunwind-dev \
    flex bison git pkg-config libelf-dev libtraceevent-dev python3-pip \
    re2c libxml2-dev libsqlite3-dev \
    autoconf automake libtool \
    && rm -rf /var/lib/apt/lists/* \
    && git clone --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git \
    && cd linux/tools/perf \
    && NO_JEVENTS=1 make \
    && cp perf /usr/bin \
    && cd / && rm -rf linux

COPY requirements.txt /app/
RUN pip3 install --no-cache-dir --break-system-packages -r /app/requirements.txt

WORKDIR /app

# ------------------------------------------------------------------
# DOWNLOAD RESOURCES
# ------------------------------------------------------------------

# Download PHP-SRC Repo
RUN git clone https://github.com/php/php-src.git /app/inputs/php-src

# ------------------------------------------------------------------

COPY php-src_pipeline.py /app/

CMD ["python3", "php-src_pipeline.py"]