FROM ubuntu:24.04

# 1. Install Dependencies
# REMOVED: python3-numpy (Let pip handle it)
RUN apt-get update && apt-get install -y \
    build-essential rsync wget curl unzip \
    python3 python3-dev libdw-dev libunwind-dev \
    flex bison git pkg-config libelf-dev libtraceevent-dev python3-pip \
    openjdk-17-jdk \
    && rm -rf /var/lib/apt/lists/* \
    && git clone --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git \
    && cd linux/tools/perf \
    && NO_JEVENTS=1 make \
    && cp perf /usr/bin \
    && cd / && rm -rf linux

# Install Bazelisk
RUN wget https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64 \
    && chmod +x bazelisk-linux-amd64 \
    && mv bazelisk-linux-amd64 /usr/bin/bazel

COPY requirements.txt /app/
RUN pip3 install --no-cache-dir --break-system-packages -r /app/requirements.txt

WORKDIR /app

# Download TensorFlow
RUN git clone https://github.com/tensorflow/tensorflow.git /app/inputs/tensorflow

COPY tensorflow_pipeline.py /app/

CMD ["python3", "tensorflow_pipeline.py"]