FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive

# 1. Install Dependencies for GPAC
# REMOVED: libavcodec-dev, libavformat-dev, etc. (To prevent version conflicts)
RUN apt-get update && apt-get install -y \
    build-essential \
    pkg-config \
    git \
    python3 \
    linux-tools-common \
    libslang2 \
    libunwind8 \
    liblzma5 \
    libnuma1 \
    libelf1 \
    libdw1 \
    libzstd1 \
    libdebuginfod1 \
    libpfm4 \
    libpython3.12 \
    libperl5.38 \
    libtraceevent1 \
    libbabeltrace1 \
    rsync \
    wget \
    curl \
    zlib1g-dev \
    libfreetype6-dev \
    libjpeg62-dev \
    libpng-dev \
    libmad0-dev \
    libfaad-dev \
    libogg-dev \
    libvorbis-dev \
    libtheora-dev \
    liba52-0.7.4-dev \
    libxv-dev \
    x11proto-video-dev \
    libgl1-mesa-dev \
    && rm -rf /var/lib/apt/lists/*

# 2. Setup paths
WORKDIR /app
RUN mkdir -p /app/inputs \
    && mkdir -p /app/output

# 3. Git fix
RUN git config --global --add safe.directory '*'

# 4. Remove default perf wrapper
RUN rm -f /usr/bin/perf

# ------------------------------------------------------------------
# DOWNLOAD RESOURCES
# ------------------------------------------------------------------

# Download GPAC Repo
RUN git clone https://github.com/gpac/gpac.git /app/inputs/gpac

# ------------------------------------------------------------------

COPY gpac_pipeline.py /app/

CMD ["python3", "gpac_pipeline.py"]