FROM ubuntu:24.04

# 1. Install Dependencies
# Added: cmake (Modern Jasper build system), libjpeg-dev, libopengl-dev
RUN apt-get update && apt-get install -y \
    build-essential rsync wget curl \
    python3 python3-dev libdw-dev libunwind-dev \
    flex bison git pkg-config libelf-dev libtraceevent-dev python3-pip \
    cmake libjpeg-dev libopengl-dev libpng-dev \
    && rm -rf /var/lib/apt/lists/* \
    && git clone --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git \
    && cd linux/tools/perf \
    && NO_JEVENTS=1 make \
    && cp perf /usr/bin \
    && cd / && rm -rf linux

COPY requirements.txt /app/
RUN pip3 install --no-cache-dir --break-system-packages -r /app/requirements.txt

WORKDIR /app

# Download Jasper Repo
RUN git clone https://github.com/jasper-software/jasper.git /app/inputs/jasper

COPY jasper_pipeline.py /app/

CMD ["python3", "jasper_pipeline.py"]