FROM ubuntu:24.04

RUN apt-get update && apt-get install -y \
    build-essential rsync wget curl \
    python3 python3-dev libdw-dev libunwind-dev \
    flex bison git pkg-config libelf-dev libtraceevent-dev python3-pip \
    libjpeg-dev libpng-dev libtiff-dev libgif-dev libwebp-dev libopenjp2-7-dev \
    ghostscript libfreetype6-dev libfontconfig1-dev \
    && rm -rf /var/lib/apt/lists/* \
    && git clone --depth 1 https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git \
    && cd linux/tools/perf \
    && NO_JEVENTS=1 make \
    && cp perf /usr/bin \
    && cd / && rm -rf linux

COPY requirements.txt /app/
RUN pip3 install --no-cache-dir --break-system-packages -r /app/requirements.txt

# 2. Setup paths
WORKDIR /app

# ------------------------------------------------------------------
# DOWNLOAD RESOURCES
# ------------------------------------------------------------------

# Download ImageMagick Repo
RUN git clone https://github.com/ImageMagick/ImageMagick.git /app/inputs/ImageMagick

# ------------------------------------------------------------------

COPY imagemagick_pipeline.py /app/

CMD ["python3", "imagemagick_pipeline.py"]